### ISSUE TITLE
Intel doesn´t work

### ISSUE THREAD

**Issue by 3DSFreaker** [Schwaggot/kellerkompanie-mods#17]
If Intel is picked up it appears in Log but there is no entry in the briefing tab.

**Comment by Katalam** [comment]
If you cgoose the standard ArmA vanilla intel there will be no intel if you doesn’t change a variable directly on the intel object.
https://community.bistudio.com/wiki/BIS_fnc_initIntelObject
Here is the Bohemia function for intel. Maybe there is the “bug”

**Comment by Schwaggot** [comment]
@Katalam Interesting, didn't know about that function, will check that out.
@3DSFreaker I actually forgot about this bug, but now it's pushed to the top of the ToDo list.
