### ISSUE TITLE
Players spawn with weapon up

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#25]
There was a time when players automatically lowered their weapon after receiving loadout, check why this is not the case anymore.

**Comment by Schwaggot** [comment]
Seems to be fixed now for loadout menu, but still happens with loadout on spawn.

**Comment by shukari** [comment]
https://community.bistudio.com/wiki/Arma_3_Actions#WeaponInHand_.2F_WeaponOnBack

**Comment by Schwaggot** [comment]
Jo, https://github.com/Schwaggot/kellerkompanie-mods/blob/master/addons/loadout/functions/fnc_giveLoadout.sqf#L348-L350
Das Ding ist, es greift nicht, ich vermute, die Waffe wird im selben Frame hinzugefügt, er macht dann automatisch die Animation "Oh, ich habe eine Waffe, erstmal zücken" und sobald das durch ist kann man erst die Waffe runternehmen. Ich führe es hier wahrscheinlich zu früh aus.

**Comment by Schwaggot** [comment]
... wobei das auch nicht erklärt warum es funzt wenn man das Loadout aus der Kiste zieht statt bei Spawn...

**Comment by shukari** [comment]
mal testen mit Verzögerung (`spawn`, `uiSleep`) und einmal mit davor `player switchMove ""`
