### ISSUE TITLE
Add garbage collector as default

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#35]
Activate deletion of corpses etc. by default, see https://github.com/TacticalBaconDevs/MainCore-Layout/blob/b8a939079000d9e9b90056a6c65644dd4f61d2d3/TB_MAINCORE.VR/description.ext#L24-L32

**Comment by shukari** [comment]
@Schwaggot unbedingt nochmal überarbeiten, ich hatte da etwas überlesen gehabt bei den Settings. https://github.com/Schwaggot/kellerkompanie-mods/blob/85bef23d414d4a4f6e137b654f784939604c20f0/addons/common/functions/fnc_3denAttributesChanged.sqf#L115-L123

Es geht um die Werte *Limit, *Removal**Min**Time und *Removal**Max**Time
Ich hatte verstanden, das sobald das *Limit überschritten ist, die Sachen nach *Removal**Min**Time bis *Removal**Max**Time gelöscht werden, **das ist aber FALSCH.**

*Removal**Max**Time = ist die Zeit die ein Körper rumliegt, wenn das *Limit noch nicht erreicht wurde (oder gleich ist)
*Removal**Min**Time = ist die Zeit die ein Körper rumliegt, wenn das Limit überschritten wurde

Das bedeutet auch, wenn ein Körper schon ewig liegt (also noch im Bereich der *Removal**Max**Time) und dann das Limit überschritten wird, gilt die *Removal**Min**Time und der Körper wird gelöscht (eigl. wird er in den Boden gezogen ^^) wenn keiner in der minPlayerDistance ist.

Quelle: https://community.bistudio.com/wiki/Description.ext#corpseLimit

**Comment by Schwaggot** [comment]
@shukari Ja die waren verwirrend, ich erinnere mich. Vielen Dank für den Hinweis.
