### ISSUE TITLE
Check assignment of Zeus

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#38]
Zeus players, which are not admin currently don't have Zeus access by default, have a look at new ACE feature for adding Zeus: https://github.com/acemod/ACE3/pull/6203

**Comment by shukari** [comment]
Befehl: ["ace_zeus_createZeus", ACE_player] call CBA_fnc_serverEvent;

Umsetzung:
- per Tastendruck: https://github.com/TacticalBaconDevs/TBMod/blob/master/addons/TBMod_main/functions/fn_shortcuts.sqf
- per ChatCommand: https://github.com/TacticalBaconDevs/TBMod/blob/master/addons/TBMod_main/functions/fn_chatCommands.sqf
- ggf wie wir mit Rechtesystem wer das darf über UUIDs oder per MissionValue (https://community.bistudio.com/wiki/getMissionConfigValue)

**Comment by Schwaggot** [comment]
Nope, still broken.

**Comment by shukari** [comment]
What is the problem? ace_zeus_createZeus or your own addZeus solution?

**Comment by Schwaggot** [comment]
Fixed with 1632a54bcda87ebcdfabc8dc20d3c4d8ce9bec14
