### ISSUE TITLE
Kellerkompanie IFA3 MG Ammo

### ISSUE THREAD

**Issue by SubitoMortem** [Schwaggot/kellerkompanie-mods#40]
Hinzufügen von Magazinen mit 75/150/250 Schuss für das FOW MG 34 und MG 42

LIB_50Rnd_792x57

ACE_isBelt = 1;
ammo = "LIB_B_792x57_Ball";
author = "AWAR";
count = 50;
descriptionShort = "50 Rounds Magazine";
displayName = "50rounds Gurttrommel";
displayNameShort = "";
initSpeed = 755;
lastRoundsTracer = 3;
mass = 14.55;
maxLeadSpeed = 25;
maxThrowHoldTime = 2;
maxThrowIntensityCoef = 1.4;
minThrowIntensityCoef = 0.3;
model = "\WW2\Assets_m\Weapons\WeaponsMagazines_m\IF_MG42_Mag.p3d";
modelSpecial = "";
nameSound = "mgun";
picture = "\WW2\Assets_t\Weapons\Equipment_t\Magazines\MachineGun_Light\M_MG42_ca.paa";
quickReload = 0;
reloadAction = "";
scope = 2;
selectionFireAnim = "zasleh";
simulation = "ProxyMagazines";
tracersEvery = 3;
type = "2* 256";
useAction = 0;
useActionTitle = "";
value = 1;
weaponpoolavailable = 1;
weight = 0;

**Comment by Schwaggot** [comment]
Introduced with latest update 03e300051a79a2eee61be3bfd29ad4fcb82a4734
