### ISSUE TITLE
CheckPBO: message is not copied to clipboard

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#58]
The error message seems to not be copied into clipboard on the client machine.

**Comment by shukari** [comment]
In multiplayer copyToClipboard is not possible -> https://community.bistudio.com/wiki/copyToClipboard

**Comment by Schwaggot** [comment]
@shukari thx, it seems I managed to ignore the big red box alltogether, I have now replaced it with calls to the ACE3 extension "ace_clipboard", which is, e.g., used by their arsenal.
