### ISSUE TITLE
Teleport to player bug

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#66]
```
20:36:43 Error in expression <ext [format ["Du wirst zu %1 verlegt.", name _destinationPlayer], "BLACK FADED"]>
20:36:43   Error position: <name _destinationPlayer], "BLACK FADED"]>
20:36:43   Error name: Typ Zeichenfolge, erwartet Objekt,Location
20:36:43 File x\keko\addons\teleport\functions\fnc_dialogTeleportToPlayer.sqf, line 8
```

**Comment by shukari** [comment]
"_destinationPlayer" ist ein String weil du die Person per [lbData](https://community.bistudio.com/wiki/lbData) https://github.com/Schwaggot/kellerkompanie-mods/blob/c5bfb31358a18e86b8db1c70487b11323c49ecc5/addons/teleport/ui/dialog_teleport.hpp#L174 hier als String rausziehst... `call compile` sollte helfen oder objektID/name verwenden.

**Comment by Schwaggot** [comment]
Das ist ja nett, ich hatte das Issue nur angelegt damit ichs net vergesse, habs mir aber noch nicht wieder angeguckt und schwupp die wupp wirds einfach gelöst. Super, thx 👍  Guck ich mir an sobald ich Zeit finde.
