### ISSUE TITLE
Module to make player spectator

### ISSUE THREAD

**Issue by Schwaggot** [Schwaggot/kellerkompanie-mods#67]
Add a module that can be dropped on a player to give him ACE spectator.

**Comment by shukari** [comment]
A snippet for you: https://github.com/TacticalBaconDevs/TBMod/blob/802135e72868de711af6ecde2aa9b0c43a16eb03/infos/debugCode.sqf#L74-L82

**Comment by Katalam** [comment]
A snippet for you too:
https://github.com/Katalam/kat_10thmods/blob/c3da211c5517c49a60d28c83bd42f06530a03b17/addons/common/CfgVehicles.hpp#L61-L66

https://github.com/Katalam/kat_10thmods/blob/master/addons/common/functions/fnc_moduleAddSpectatorMenu3den.sqf

https://github.com/Katalam/kat_10thmods/blob/master/addons/common/functions/fnc_addSpectatorMenu.sqf

**Comment by Schwaggot** [comment]
Thx guys :* #nohomo

**Comment by Schwaggot** [comment]
closed with 7213bdab1016cbe92b5004e597ef64eb0ca21223
